<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net472</TargetFramework>
        <LangVersion>11.0</LangVersion>
        <Nullable>enable</Nullable>
        <GenerateDependencyFile>false</GenerateDependencyFile>
    </PropertyGroup>

    <ItemDefinitionGroup>
        <Reference>
            <Private>false</Private>
        </Reference>
    </ItemDefinitionGroup>

    <ItemGroup>
      <Reference Include="0Harmony20">
        <HintPath>E:\Steam\Install\steamapps\workshop\content\1189490\2824349934\BepInEx\core\0Harmony20.dll</HintPath>
      </Reference>
      <Reference Include="Assembly-CSharp">
        <HintPath>E:\Steam\Install\steamapps\common\觅长生\觅长生_Data\Managed\Assembly-CSharp.dll</HintPath>
      </Reference>
      <Reference Include="Assembly-CSharp-firstpass">
        <HintPath>E:\Steam\Install\steamapps\common\觅长生\觅长生_Data\Managed\Assembly-CSharp-firstpass.dll</HintPath>
      </Reference>
      <Reference Include="BepInEx">
        <HintPath>E:\Steam\Install\steamapps\workshop\content\1189490\2824349934\BepInEx\core\BepInEx.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine">
        <HintPath>E:\Steam\Install\steamapps\common\觅长生\觅长生_Data\Managed\UnityEngine.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.CoreModule">
        <HintPath>E:\Steam\Install\steamapps\common\觅长生\觅长生_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.IMGUIModule">
        <HintPath>E:\Steam\Install\steamapps\common\觅长生\觅长生_Data\Managed\UnityEngine.IMGUIModule.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
